name: Build iOS

on:
  workflow_dispatch:

  push:

jobs:
  extract:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install pkg-config bison flex ninja meson libclc cmake xorgproto libxfixes tree vulkan-tools
        brew install llvm
        brew install --only-dependencies mesa
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Mako with Python
      run: |
           python -m pip install --upgrade pip
           pip install mako
#    - name: Prepare Vulkan SDK
#      uses: humbletim/setup-vulkan-sdk@v1.2.0
#      with:
#       vulkan-query-version: 1.3.204.0
#       vulkan-components: Vulkan-Headers, Vulkan-Loader
#       vulkan-use-cache: false

    - name: Build Mesa
      run: |
        meson setup build -Dgallium-drivers=zink,swrast -Dosmesa=true -Dvulkan-drivers= --prefix=/tmp/ump -Dmoltenvk-dir=/usr/local/Cellar/molten-vk/1.2.7
        pwd
        ls
        tree
        ninja -C build/ install

    - name: "Upload installed mesa"
      uses: actions/upload-artifact@v4
      with:
        name: built
        path: /tmp/ump
